.\" Manpage for system-monitoring-center.
.\" Author: Hakan Dündar <hakandundar34coding@gmail.com>
.\" Date: 12/11/2021
.\" Language: English
.TH "system-monitoring-center" "1" "" "system-monitoring-center" "man page"
.SH NAME
system-monitoring-center \- Provides information about system performance and usage.
.SH SYNOPSIS
system-monitoring-center
.SH DESCRIPTION
Provides information about CPU/RAM/Disk/Network/GPU performance, sensors, processes, users, storage, startup programs, services, environment variables and system.
.SH OPTIONS
system-monitoring-center has no command line options.
.SH MORE INFORMATION
Perform mouse hover action on GUI objects (such as labels, menu items, buttons, etc.) to get explanatory information.
